[tasks.cargo-build-example]
args = ["build", "--target", "wasm32-unknown-unknown", "--example", "${CARGO_MAKE_TASK_ARGS}", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"
dependencies = ["install-wasm-target"]

[tasks.build-example]
args = ["--remove-name-section", "--remove-producers-section", "--out-dir", "${TARGET_DIR}", "--out-name", "wasm", "--target", "web", "--no-typescript", "${CARGO_WASM_EXAMPLE_PATH}"]
command = "wasm-bindgen"
dependencies = ["cargo-build-example", "install-wasm-bindgen-cli"]